### ISSUE TITLE
Add colorblind-friendly colormap(s)

### ISSUE THREAD

**Issue by iannesbitt** [usgs/volcano-core#90]
This is duplicated from an issue downstream in [SWARM](https://github.com/usgs/swarm).

## Issue background (https://github.com/usgs/swarm/issues/275)
I have a suggestion which would not only help colorblind users interpret spectrograms in SWARM, it would also help those of us who can see the full spectrum. SWARM's spectrogram uses a rainbow color scale, which is ineffective at conveying numeric information properly, and virtually impossible to read for most colorblind users. @kwinkunks shared this image of a colorized LiDAR elevation dataset [on Twitter](https://twitter.com/kwinkunks/status/1121844842932449282) not long ago, which is a good demonstration of how rainbow colormaps distort our visual perception of data:
![image](https://user-images.githubusercontent.com/18689918/58981922-5eb64a00-87a1-11e9-8700-07dbe0d8ecf0.png)
Both colorblind and non-colorblind viewers will notice that the two right-hand color scales are more difficult to interpret in the blue and green bands, while those on the left convey stunning detail of abandoned river meanders in those same areas. This is because, in essence, the brightness of the image does not vary co-linearly with hue, and human eyes are much more attuned to perceive dark/light differences than differences in hue.

In light of this, I propose changing SWARM's spectrogram color scale to something perceptually uniform and linear. You can [read about perceptual uniformity/linearity here](https://bids.github.io/colormap/). At this link there are also public domain (Creative Commons 0—i.e. "no rights reserved") colormaps available in several languages, which I think can be ported to Java fairly easily.

## Potential resolution
Add a new file in [gov.usgs.volcanoes.core.legacy.plot.color](https://github.com/usgs/volcano-core/tree/master/src/main/java/gov/usgs/volcanoes/core/legacy/plot/color) called `Inferno.java` that extends `Spectrum.java` and use RGB values from an open-source CC0-licensed project like [this one](https://github.com/politiken-journalism/scale-color-perceptual/blob/master/rgb/inferno.json), which looks like the spectrum below.
![image](https://user-images.githubusercontent.com/18689918/60044750-0df38c00-9691-11e9-9d68-e817b0bc7bce.png)
I realize folks are busy so I may take a crack at this myself and submit a pull request for it, but it won't be for a couple of months and I'd need to learn some Java in order to do so.

**Comment by dnorgaard-usgs** [comment]
Hi.  I think your solution will work.  It appears the Jet2 spectrum, derived from earthworm's sgram module, is used in SpectrogramRenderer.  Instead of replacing the default color map though, I would like to add an option in Swarm that supports this new color map if user chooses.  Many folks are likely accustomed to the current color map and may balk at using another.

Looks like the important bit is the paletteBytes, which is used to create palette from https://docs.oracle.com/javase/7/docs/api/java/awt/image/IndexColorModel.html#IndexColorModel(int,%20int,%20byte[],%20int,%20boolean).

**Comment by dnorgaard-usgs** [comment]
I took a stab at creating Inferno.java.  I multiplied the values in the json file you provided by 255 and cast it to byte.  Not sure if that was the right way or not, but seems to work.  

![clipboard](https://user-images.githubusercontent.com/25251719/64391239-e576ff00-cffc-11e9-98f6-33c5170ff5e3.png)

vs

![clipboard2](https://user-images.githubusercontent.com/25251719/64391365-3edf2e00-cffd-11e9-8991-a92e4f44884e.png)

What do you think?

**Comment by iannesbitt** [comment]
I love it Diana, thank you so much for taking the time to implement this! Cheers!

I imagine you've made the changes to the downstream already, so I can go ahead and close this issue if you think it's ready. Looking forward to seeing the changes in an upcoming binary.

**Comment by dnorgaard-usgs** [comment]
Yes, the changes here are committed.  Working on Swarm side at the moment.  So far so good.  Should be good to go in next release.
